//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unlockfps_nc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unlockfps_nc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have detected errors in the FPS Unlocker&apos;s configuration file. We will attempt its repair. If the program launches normally, this will indicate that the repair was successful. If this message keeps appearing, please delete the configuration file (unlocker.config.json) or contact the developer.
        ///
        ///{0}.
        /// </summary>
        internal static string ConfigService_WeHaveDetectedErrorsInTheConfigFile {
            get {
                return ResourceManager.GetString("ConfigService_WeHaveDetectedErrorsInTheConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        internal static string MainForm_AnErrorOccurred {
            get {
                return ResourceManager.GetString("MainForm_AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin FPS Unlocker (Current limit: {0}).
        /// </summary>
        internal static string MainForm_GenshinFPSUnlocker_CurrentLimit {
            get {
                return ResourceManager.GetString("MainForm_GenshinFPSUnlocker_CurrentLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;StellaPath&apos; not found. Is the Genshin Stella Mod definitely installed?.
        /// </summary>
        internal static string MainForm_KeyStellaPathNotFound {
            get {
                return ResourceManager.GetString("MainForm_KeyStellaPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key &apos;SOFTWARE\Stella Mod Launcher&apos; not found. Is the Genshin Stella Mod definitely installed?.
        /// </summary>
        internal static string MainForm_RegistryKeySOFTWAREStellaModLauncherNotFound {
            get {
                return ResourceManager.GetString("MainForm_RegistryKeySOFTWAREStellaModLauncherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another unlocker is already running..
        /// </summary>
        internal static string Program_AnotherUnlockerIsAlreadyRunning {
            get {
                return ResourceManager.GetString("Program_AnotherUnlockerIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File:
        ///{0}
        ///
        ///Only native x64 dlls are supported..
        /// </summary>
        internal static string SettingsForm_InvaildFile {
            get {
                return ResourceManager.GetString("SettingsForm_InvaildFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path: {0}.
        /// </summary>
        internal static string SetupForm_CurrentPath {
            get {
                return ResourceManager.GetString("SetupForm_CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find process path. Please use &quot;Browse&quot; instead.
        /// </summary>
        internal static string SetupForm_FailedToFindProcessPath {
            get {
                return ResourceManager.GetString("SetupForm_FailedToFindProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} installation of the game.
        /// </summary>
        internal static string SetupForm_Found_0_installationOfTheGame {
            get {
                return ResourceManager.GetString("SetupForm_Found_0_installationOfTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Found!
        ///{0}.
        /// </summary>
        internal static string SetupForm_GameFound {
            get {
                return ResourceManager.GetString("SetupForm_GameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the game exe.
        ///GenshinImpact.exe or YuanShen.exe..
        /// </summary>
        internal static string SetupForm_PleaseSelectTheGameExe {
            get {
                return ResourceManager.GetString("SetupForm_PleaseSelectTheGameExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string SetupForm_Searching {
            get {
                return ResourceManager.GetString("SetupForm_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not the right place..
        /// </summary>
        internal static string SetupForm_ThatsNotTheRightPlace {
            get {
                return ResourceManager.GetString("SetupForm_ThatsNotTheRightPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
