//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unlockfps_nc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unlockfps_nc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create shared memory..
        /// </summary>
        internal static string IpcService_Start_FailedToCreateSharedMemory {
            get {
                return ResourceManager.GetString("IpcService_Start_FailedToCreateSharedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load stub module: {0}
        ///{1}.
        /// </summary>
        internal static string IpcService_Start_FailedToLoadStubModule {
            get {
                return ResourceManager.GetString("IpcService_Start_FailedToLoadStubModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to post thread message: {0}
        ///{1}.
        /// </summary>
        internal static string IpcService_Start_FailedToPostThreadMessage {
            get {
                return ResourceManager.GetString("IpcService_Start_FailedToPostThreadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set window hook: {0}
        ///{1}.
        /// </summary>
        internal static string IpcService_Start_FailedToSetWindowHook {
            get {
                return ResourceManager.GetString("IpcService_Start_FailedToSetWindowHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the unlocker..
        /// </summary>
        internal static string IpcService_Start_FailedToStartUnlocker {
            get {
                return ResourceManager.GetString("IpcService_Start_FailedToStartUnlocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genshin FPS Unlocker (current limit: {0}).
        /// </summary>
        internal static string MainForm_NotifyAndHide_GenshinFPSUnlockerCurrentLimit_ {
            get {
                return ResourceManager.GetString("MainForm_NotifyAndHide_GenshinFPSUnlockerCurrentLimit_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry key &quot;StellaPath&quot; was not found. Are you sure Genshin Stella Mod is installed?.
        /// </summary>
        internal static string MainForm_OpenStella_Click_TheRegistryKeyStellaPathWasNotFoundAreYouSureGenshinStellaModIsInstalled {
            get {
                return ResourceManager.GetString("MainForm_OpenStella_Click_TheRegistryKeyStellaPathWasNotFoundAreYouSureGenshinSte" +
                        "llaModIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string MainForm_ViewCfg_FileNotFound {
            get {
                return ResourceManager.GetString("MainForm_ViewCfg_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unlocker.config.json file was not found..
        /// </summary>
        internal static string MainForm_ViewCfg_TheUnlockerConfigJsonFileWasNotFound {
            get {
                return ResourceManager.GetString("MainForm_ViewCfg_TheUnlockerConfigJsonFileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateProcess failed ({0})
        ///{1}.
        /// </summary>
        internal static string ProcessService_StartGame_CreateProcessFailed {
            get {
                return ResourceManager.GetString("ProcessService_StartGame_CreateProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enable HDR: {0}.
        /// </summary>
        internal static string ProcessService_StartGame_FailedToEnableHDR {
            get {
                return ResourceManager.GetString("ProcessService_StartGame_FailedToEnableHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of the game is already running. Please close it first..
        /// </summary>
        internal static string ProcessService_StartGame_GameAlreadyRunning {
            get {
                return ResourceManager.GetString("ProcessService_StartGame_GameAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game executable not found:
        ///{0}
        ///
        ///Please configure the correct path in Setup..
        /// </summary>
        internal static string ProcessService_StartGame_GameNotFound {
            get {
                return ResourceManager.GetString("ProcessService_StartGame_GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumProcessModulesEx failed ({0})
        ///{1}.
        /// </summary>
        internal static string ProcessUtils_GetModuleBase_EnumProcessModulesExFailed {
            get {
                return ResourceManager.GetString("ProcessUtils_GetModuleBase_EnumProcessModulesExFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not place this tool in the game folder!.
        /// </summary>
        internal static string Program_Main_DoNotPlaceThisToolInTheGameFolder {
            get {
                return ResourceManager.GetString("Program_Main_DoNotPlaceThisToolInTheGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the game exe:
        ///GenshinImpact.exe or YuanShen.exe.
        /// </summary>
        internal static string SetupForm_BtnBrowse_Click_PleaseSelectTheGameExe_GenshinImpactExeOrYuanShenExe {
            get {
                return ResourceManager.GetString("SetupForm_BtnBrowse_Click_PleaseSelectTheGameExe_GenshinImpactExeOrYuanShenExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not the right place..
        /// </summary>
        internal static string SetupForm_BtnBrowse_Click_ThatSNotTheRightPlace {
            get {
                return ResourceManager.GetString("SetupForm_BtnBrowse_Click_ThatSNotTheRightPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find process path. Please use &quot;Browse&quot; instead..
        /// </summary>
        internal static string SetupForm_PollProcess_FailedToFindProcessPathPleaseUseBrowseInstead {
            get {
                return ResourceManager.GetString("SetupForm_PollProcess_FailedToFindProcessPathPleaseUseBrowseInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game found!
        ///{0}.
        /// </summary>
        internal static string SetupForm_PollProcess_GameFound_ {
            get {
                return ResourceManager.GetString("SetupForm_PollProcess_GameFound_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong:
        ///{0}.
        /// </summary>
        internal static string SetupForm_SearchGamePath_SomethingWentWrong_ExMessage {
            get {
                return ResourceManager.GetString("SetupForm_SearchGamePath_SomethingWentWrong_ExMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string SetupForm_Searching {
            get {
                return ResourceManager.GetString("SetupForm_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} installation of the game.
        /// </summary>
        internal static string SetupForm_UpdateGamePathUi_Found0InstallationOfTheGame {
            get {
                return ResourceManager.GetString("SetupForm_UpdateGamePathUi_Found0InstallationOfTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game installations found!.
        /// </summary>
        internal static string SetupForm_UpdateGamePathUi_NoGameInstallationsFound {
            get {
                return ResourceManager.GetString("SetupForm_UpdateGamePathUi_NoGameInstallationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
